name: spot
description: Find local video posts
version: 1.4.2+64
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.10.5+9
  flutter_bloc: ^8.1.4
  google_maps_flutter: ^2.0.1
  video_player: ^2.0.2
  flutter_ffmpeg: ^0.4.2
  path_provider: ^2.0.1
  geolocator: ^11.0.0
  supabase: ^2.0.8
  flutter_feather_icons: ^2.0.0+1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  flutter_cache_manager: ^3.0.1
  flutter_markdown: ^0.6.1
  rxdart: ^0.27.7
  geocoding: ^3.0.0
  share: ^2.0.1
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.9
  flutter_video_info: ^1.2.0
  shared_preferences: ^2.0.6
  google_maps_cluster_manager: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.6
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  assets:
    - assets/images/
    - assets/md/
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher/icon.png'
  adaptive_icon_foreground: 'assets/launcher/foreground.png'
  adaptive_icon_background: 'assets/launcher/background.png'
